pipeline {
    agent {
        docker {
            image 'cypress/included:15.11.0'
        }
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('cypress-course') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Cypress Tests') {
            steps {
                dir('cypress-course') {
                    sh 'npx cypress run'
                }
            }
        }

    }

    post {
        always {
            archiveArtifacts artifacts: 'cypress-course/cypress/videos/**', allowEmptyArchive: true
            archiveArtifacts artifacts: 'cypress-course/cypress/screenshots/**', allowEmptyArchive: true
        }
    }
}